---
# This Playbook deploys a KairosDB cluster on Amazon EC2

- name: Provisioning infrastructure for Cassandra cluster
  hosts: localhost
  gather_facts: True
  vars:
    aws_instance_number: "1"
    clustergroup: "cassandra_cluster"
    aws_key_file: "{{ ansible_env.AWS_KEY_FILE }}"
  vars_files:
  - roles/vil/vars/cassandra.yml
  roles:
  - role: vil

- name: Provisioning infrastructure for YCSB cluster
  hosts: localhost
  gather_facts: True
  vars:
    aws_instance_number: "1"
    clustergroup: "ycsb_cluster"
    aws_key_file: "{{ ansible_env.AWS_KEY_FILE }}"
  vars_files:
  - roles/vil/vars/ycsb.yml
  roles:
  - role: vil

- name: Wait for SSH
  hosts: localhost
  tasks:
  - wait_for: timeout=60

- name: Setting up volumes in testbed
  hosts: tag_cassandra_true
  user: ubuntu
  gather_facts: true
  vars_files: 
  - group_vars/ubuntu
  - roles/vil/vars/cassandra.yml
  tasks:
    - set_fact:
        sutdevice="/dev/md0"
        fs_blocksize="4096"
      when: ebs_volume_list|length > 1
    - include: tasks/raid.yml
      when: ebs_volume_list|length > 1
    - set_fact:
        sutdevice="/dev/xvdb"
        fs_blocksize="4096"
      when: ebs_volume_list|length == 1 
    - include: tasks/mounted_dev.yml
      when: ebs_volume_list|length == 1


# FIXME: Wait for SSH to come up
- hosts: cassandra_cluster:ycsb_cluster
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  vars:
    aws_region: "eu-west-1"
    aws_key_file: "{{ ansible_env.AWS_KEY_FILE }}"
    aws_access_key_id: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
    aws_secret_access_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
  vars_files:
  - "group_vars/ubuntu"
  - "group_vars/aws"
  roles:
  - role: aws
  # - role: ssh
  - role: java
  - role: dstat

- hosts: cassandra_cluster
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  vars_files:
  - "group_vars/ubuntu"
  - "group_vars/aws"
  roles:
  - role: cassandra

- hosts: ycsb_cluster
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  vars_files:
  - "group_vars/ubuntu"
  - "group_vars/aws"
  roles:
  - role: ycsb
