---
# file: /roles/cassandra/tasks/main.yml

- name: Create temporary dir 'tmp' on remote node
  file: >
    path={{ tmp_dir }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Download tar ball from S3
  get_url: >
    url={{ cassandra_uri }}
    dest={{ tmp_dir }}

- name: Untar tar ball
  command: tar -xvf {{ tmp_dir }}/{{ cassandra_tar_name }} -C {{ tmp_dir }}

  # touch untared dir, but add/remove some permissions
- file: >
    path={{ tmp_dir }}/{{ cassandra_untar_name }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Remove install dir
  sudo: yes
  file: > 
    path={{ cassandra_home }}
    state=absent

- name: Create target dir on remote node
  sudo: yes
  file: >
    path={{ cassandra_home }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Copy content of extracted tar ball to install dir
  sudo: yes
  shell: "mv {{ tmp_dir }}/{{ cassandra_untar_name }}/* {{ cassandra_home }}/"

- name: Remove conf file '$CASSANDRA_HOME/conf/cassandra.yaml'
  sudo: yes
  file: > 
    path={{ cassandra_home }}/conf/cassandra.yaml
    state=absent

- name: Create conf file '$CASSANDRA_HOME/conf/cassandra.yaml'
  template: >
    src=cassandra.yaml.j2
    dest={{ cassandra_home}}/conf/cassandra.yaml
    owner={{ user }}
    group={{ user }}
    mode=0755

- name: Create CQL_HOME dir on remote node
  sudo: yes
  file: >
    path={{ cql_home }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

# Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version
- name: 
  sudo: yes
  copy: >
    src={{ setup_ycsb_cql }}
    dest={{ cql_home }}/
    owner={{ user }}
    group={{ user }}
    mode="0755"

### OS VARIABLES ###
# /etc/profile
- name: Set CASSANDRA_HOME in /etc/profile
  sudo: yes
  lineinfile: >
    dest=/etc/profile
    line="export CASSANDRA_HOME={{ cassandra_home }}"

- name: Add CASSANDRA_HOME to PATH in /etc/profile
  sudo: yes
  lineinfile: >
    dest=/etc/profile
    line="export PATH=$PATH:$CASSANDRA_HOME/bin"

- name: Set CQLSH_HOST in /etc/profile
  sudo: yes
  lineinfile: >
    dest=/etc/profile
    line="export CQLSH_HOST={{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"


# /etc/bash.bashrc
- name: Set CASSANDRA_HOME in /etc/bash.bashrc
  sudo: yes
  lineinfile: >
    dest="/etc/bash.bashrc"
    line="export CASSANDRA_HOME={{ cassandra_home }}"

- name: Add CASSANDRA_HOME to PATH in /etc/bash.bashrc
  sudo: yes
  lineinfile: >
    dest="/etc/bash.bashrc"
    line="export PATH=$PATH:$CASSANDRA_HOME/bin"

- name: Set CQLSH_HOST in /etc/bash.bashrc
  sudo: yes
  lineinfile: >
    dest="/etc/bash.bashrc"
    line="export CQLSH_HOST={{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"


# /etc/skel/.bashrc
- name: Set CASSANDRA_HOME in /etc/skel/.bashrc
  sudo: yes
  lineinfile: >
    dest=/etc/skel/.bashrc
    line="export CASSANDRA_HOME={{ cassandra_home }}"

- name: Add CASSANDRA_HOME to PATH in /etc/skel/.bashrc
  sudo: yes
  lineinfile: >
    dest=/etc/skel/.bashrc
    line="export PATH=$PATH:$CASSANDRA_HOME/bin"

- name: Set CQLSH_HOST in /etc/skel/.bashrc
  sudo: yes
  lineinfile: >
    dest=/etc/skel/.bashrc
    line="export CQLSH_HOST={{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"


# /home/ubuntu/.bashrc
- name: Set CASSANDRA_HOME in /home/ubuntu/.bashrc
  sudo: yes
  lineinfile: >
    dest=/home/ubuntu/.bashrc
    line="export CASSANDRA_HOME={{ cassandra_home }}"
    
- name: Add CASSANDRA_HOME to PATH in /home/ubuntu/.bashrc
  sudo: yes
  lineinfile: >
    dest=/home/ubuntu/.bashrc
    line="export PATH=$PATH:$CASSANDRA_HOME/bin"

- name: Set CQLSH_HOST in /home/ubuntu/.bashrc
  sudo: yes
  lineinfile: >
    dest=/home/ubuntu/.bashrc
    line="export CQLSH_HOST={{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"


# /root/.bashrc
- name: Set CASSANDRA_HOME in /root/.bashrc
  sudo: yes
  lineinfile: >
    dest=/root/.bashrc
    line="export CASSANDRA_HOME={{ cassandra_home }}"

- name: Set CASSANDRA_HOME in /root/.bashrc
  sudo: yes
  lineinfile: >
    dest=/root/.bashrc
    line="export PATH=$PATH:$CASSANDRA_HOME/bin"

- name: Set CQLSH_HOST in /root/.bashrc
  sudo: yes
  lineinfile: >
    dest=/root/.bashrc
    line="export CQLSH_HOST={{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"

- name: Remove tmp dir
  sudo: yes
  file: > 
    path={{ tmp_dir }}
    state=absent
