---
# file: /roles/kairos/tasks/main.yml

- name: Create temporary dir 'tmp' on remote node
  file: >
    path={{ tmp_dir }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Download KairosDB tar ball from S3
  get_url: >
    url={{ kairos_uri }}
    dest={{ tmp_dir }}

- name: Untar KairosDB tar ball
  command: tar -xvf {{ tmp_dir }}/{{ kairos_tar_name }} -C {{ tmp_dir }}

  # touch untared dir, but add/remove some permissions
- file: >
    path={{ tmp_dir }}/{{ kairos_untar_name }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Remove KairosDB install dir
  sudo: yes
  file: > 
    path={{ kairos_install_dir }}
    state=absent

- name: Create target dir on remote node
  sudo: yes
  file: >
    path={{ kairos_home }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Copy content of extracted tar ball to install dir
  sudo: yes
  shell: "mv {{ tmp_dir }}/{{ kairos_untar_name }}/* {{ kairos_home }}/"

- name: Remove conf file '$KAIROSDB_HOME/conf/kairosdb.properties'
  sudo: yes
  file: > 
    path={{ kairos_home }}/conf/kairosdb.properties
    state=absent

- name: Create conf file '$KAIROSDB_HOME/conf/kairosdb.properties'
  template: >
    src=kairosdb.properties.j2
    dest={{ kairos_home}}/conf/kairosdb.properties
    owner={{ user }}
    group={{ user }}
    mode=0755

- name: Remove tmp dir
  sudo: yes
  file: > 
    path={{ tmp_dir }}
    state=absent
